/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Wiew;

/**
 *
 * @author jairo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBSenhaTxt = new javax.swing.JLabel();
        LBUserTxt = new javax.swing.JLabel();
        LBLoginTxt = new javax.swing.JLabel();
        LBBackGrLogin = new javax.swing.JLabel();
        LBLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBSenhaTxt.setBackground(new java.awt.Color(255, 255, 255));
        LBSenhaTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LBSenhaTxt.setForeground(new java.awt.Color(255, 255, 255));
        LBSenhaTxt.setText("Senha");
        getContentPane().add(LBSenhaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 110, 40));

        LBUserTxt.setBackground(new java.awt.Color(255, 255, 255));
        LBUserTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LBUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        LBUserTxt.setText("Usuario");
        getContentPane().add(LBUserTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 150, 40));

        LBLoginTxt.setBackground(new java.awt.Color(255, 255, 255));
        LBLoginTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LBLoginTxt.setForeground(new java.awt.Color(255, 255, 255));
        LBLoginTxt.setText("Login");
        getContentPane().add(LBLoginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 100, 40));

        LBBackGrLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wiew/Imagens/painel-login.png"))); // NOI18N
        getContentPane().add(LBBackGrLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 580, 750));

        LBLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wiew/Imagens/Logo.jpg"))); // NOI18N
        LBLogin.setLabelFor(LBLogin);
        LBLogin.setToolTipText("");
        getContentPane().add(LBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 775, 1168));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBBackGrLogin;
    private javax.swing.JLabel LBLogin;
    private javax.swing.JLabel LBLoginTxt;
    private javax.swing.JLabel LBSenhaTxt;
    private javax.swing.JLabel LBUserTxt;
    // End of variables declaration//GEN-END:variables
}
